import type { UMLModel } from "@umlstudio/core"
import {
  buildKernelModel,
  pluralize,
  toKebabCase,
  toCamelCase,
  type KernelEntity,
  type KernelModel,
  type KernelScalarColumn,
} from "@umlstudio/core/export"
import type {
  OpenApiComponents,
  OpenApiGenerationOptions,
  OpenApiOperation,
  OpenApiPathItem,
  OpenApiSchema,
  OpenApiServer,
  OpenApiSpec,
  OpenApiTag,
} from "./types.js"

/** Maps a Java / UML scalar type to an OpenAPI 3.0 schema. */
export function mapScalarToOpenApiSchema(
  scalar: KernelScalarColumn,
  enums: Map<string, string[]>
): OpenApiSchema {
  if (scalar.enumerated && enums.has(scalar.javaType)) {
    return {
      type: "string",
      enum: enums.get(scalar.javaType),
      description: `Enumeration ${scalar.javaType}`,
    }
  }

  const jt = scalar.javaType.toLowerCase()

  if (jt === "string" || jt === "text" || jt === "char" || jt === "character") {
    return { type: "string", example: `sample_${scalar.columnName}` }
  }
  if (jt === "long") {
    return { type: "integer", format: "int64", example: 1 }
  }
  if (jt === "integer" || jt === "int" || jt === "short" || jt === "byte") {
    return { type: "integer", format: "int32", example: 10 }
  }
  if (jt === "double" || jt === "float" || jt === "bigdecimal") {
    return { type: "number", format: "double", example: 99.95 }
  }
  if (jt === "boolean") {
    return { type: "boolean", example: true }
  }
  if (jt === "localdate" || jt === "date") {
    return { type: "string", format: "date", example: "2026-01-15" }
  }
  if (jt === "localdatetime" || jt === "timestamp") {
    return {
      type: "string",
      format: "date-time",
      example: "2026-01-15T12:00:00Z",
    }
  }

  return { type: "string", example: `sample_${scalar.columnName}` }
}

/** Builds the schema for the `{Entity}Request` DTO. */
export function buildRequestSchema(
  entity: KernelEntity,
  enums: Map<string, string[]>
): OpenApiSchema {
  const properties: Record<string, OpenApiSchema> = {}
  const required: string[] = []

  for (const s of entity.scalars) {
    // Skip autogenerated id from request body
    if (s.id) continue

    const propName = toCamelCase(s.columnName)
    properties[propName] = mapScalarToOpenApiSchema(s, enums)

    if (!s.nullable) {
      required.push(propName)
    }
  }

  // Foreign key references for many-to-one relations
  for (const r of entity.relations) {
    if (r.kind === "many-to-one") {
      const fkName = r.joinColumn ? toCamelCase(r.joinColumn) : `${toCamelCase(r.targetEntity)}Id`
      properties[fkName] = {
        type: "integer",
        format: "int64",
        description: `Foreign key to ${r.targetEntity}`,
        example: 1,
      }
      if (!r.nullable) {
        required.push(fkName)
      }
    }
  }

  return {
    type: "object",
    description: `Request payload for creating or updating a ${entity.className}`,
    properties,
    ...(required.length > 0 ? { required } : {}),
  }
}

/** Builds the schema for the `{Entity}Response` DTO. */
export function buildResponseSchema(
  entity: KernelEntity,
  enums: Map<string, string[]>
): OpenApiSchema {
  const properties: Record<string, OpenApiSchema> = {}
  const required: string[] = []

  for (const s of entity.scalars) {
    const propName = toCamelCase(s.columnName)
    properties[propName] = mapScalarToOpenApiSchema(s, enums)
    if (s.id || !s.nullable) {
      required.push(propName)
    }
  }

  for (const r of entity.relations) {
    if (r.kind === "many-to-one") {
      const fkName = r.joinColumn ? toCamelCase(r.joinColumn) : `${toCamelCase(r.targetEntity)}Id`
      properties[fkName] = {
        type: "integer",
        format: "int64",
        description: `Referenced ${r.targetEntity} identifier`,
        example: 1,
      }
    } else if (r.kind === "one-to-many" || r.kind === "many-to-many") {
      const listName = `${toCamelCase(pluralize(r.targetEntity))}Ids`
      properties[listName] = {
        type: "array",
        items: { type: "integer", format: "int64" },
        description: `List of associated ${r.targetEntity} identifiers`,
        example: [1, 2],
      }
    }
  }

  return {
    type: "object",
    description: `Response payload for ${entity.className}`,
    properties,
    ...(required.length > 0 ? { required } : {}),
  }
}

/** Builds the standard ApiError schema. */
export function buildApiErrorSchema(): OpenApiSchema {
  return {
    type: "object",
    description: "Standard API error response",
    properties: {
      timestamp: {
        type: "string",
        format: "date-time",
        example: "2026-09-20T12:00:00Z",
      },
      status: {
        type: "integer",
        format: "int32",
        example: 404,
      },
      error: {
        type: "string",
        example: "Not Found",
      },
      message: {
        type: "string",
        example: "Entity with specified id does not exist",
      },
      path: {
        type: "string",
        example: "/api/clientes/1",
      },
    },
    required: ["timestamp", "status", "error", "message", "path"],
  }
}

/** Builds CRUD operations for a given entity. */
export function buildEntityPaths(entity: KernelEntity): {
  collectionPath: string
  collectionItem: OpenApiPathItem
  itemPath: string
  itemItem: OpenApiPathItem
} {
  const route = pluralize(toKebabCase(entity.className))
  const tag = entity.className
  const reqRef = `#/components/schemas/${entity.className}Request`
  const resRef = `#/components/schemas/${entity.className}Response`
  const errRef = "#/components/schemas/ApiError"

  const collectionPath = `/api/${route}`
  const itemPath = `/api/${route}/{id}`

  const listOperation: OpenApiOperation = {
    tags: [tag],
    summary: `List all ${pluralize(entity.className)}`,
    description: `Retrieves all persisted instances of ${entity.className}.`,
    operationId: `getAll${pluralize(entity.className)}`,
    responses: {
      "200": {
        description: `Successfully retrieved list of ${pluralize(entity.className)}.`,
        content: {
          "application/json": {
            schema: {
              type: "array",
              items: { $ref: resRef },
            },
          },
        },
      },
    },
  }

  const createOperation: OpenApiOperation = {
    tags: [tag],
    summary: `Create a new ${entity.className}`,
    description: `Persists a new ${entity.className} entity in the database.`,
    operationId: `create${entity.className}`,
    requestBody: {
      description: `Payload for the new ${entity.className}`,
      required: true,
      content: {
        "application/json": {
          schema: { $ref: reqRef },
        },
      },
    },
    responses: {
      "201": {
        description: `${entity.className} created successfully.`,
        content: {
          "application/json": {
            schema: { $ref: resRef },
          },
        },
      },
      "400": {
        description: "Invalid request payload or validation failed.",
        content: {
          "application/json": {
            schema: { $ref: errRef },
          },
        },
      },
    },
  }

  const getByIdOperation: OpenApiOperation = {
    tags: [tag],
    summary: `Get ${entity.className} by ID`,
    description: `Retrieves a specific ${entity.className} by its unique identifier.`,
    operationId: `get${entity.className}ById`,
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        description: `Unique identifier of the ${entity.className}`,
        schema: { type: "integer", format: "int64" },
      },
    ],
    responses: {
      "200": {
        description: `${entity.className} found.`,
        content: {
          "application/json": {
            schema: { $ref: resRef },
          },
        },
      },
      "404": {
        description: `${entity.className} not found.`,
        content: {
          "application/json": {
            schema: { $ref: errRef },
          },
        },
      },
    },
  }

  const updateOperation: OpenApiOperation = {
    tags: [tag],
    summary: `Update ${entity.className} by ID`,
    description: `Updates an existing ${entity.className} identified by ID.`,
    operationId: `update${entity.className}`,
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        description: `Unique identifier of the ${entity.className}`,
        schema: { type: "integer", format: "int64" },
      },
    ],
    requestBody: {
      description: `Updated payload for ${entity.className}`,
      required: true,
      content: {
        "application/json": {
          schema: { $ref: reqRef },
        },
      },
    },
    responses: {
      "200": {
        description: `${entity.className} updated successfully.`,
        content: {
          "application/json": {
            schema: { $ref: resRef },
          },
        },
      },
      "400": {
        description: "Validation error in request payload.",
        content: {
          "application/json": {
            schema: { $ref: errRef },
          },
        },
      },
      "404": {
        description: `${entity.className} not found.`,
        content: {
          "application/json": {
            schema: { $ref: errRef },
          },
        },
      },
    },
  }

  const deleteOperation: OpenApiOperation = {
    tags: [tag],
    summary: `Delete ${entity.className} by ID`,
    description: `Deletes the ${entity.className} entity identified by ID.`,
    operationId: `delete${entity.className}`,
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        description: `Unique identifier of the ${entity.className}`,
        schema: { type: "integer", format: "int64" },
      },
    ],
    responses: {
      "204": {
        description: `${entity.className} deleted successfully (No Content).`,
      },
      "404": {
        description: `${entity.className} not found.`,
        content: {
          "application/json": {
            schema: { $ref: errRef },
          },
        },
      },
    },
  }

  return {
    collectionPath,
    collectionItem: {
      get: listOperation,
      post: createOperation,
    },
    itemPath,
    itemItem: {
      get: getByIdOperation,
      put: updateOperation,
      delete: deleteOperation,
    },
  }
}

/**
 * Builds a complete, valid OpenAPI 3.0.3 document from a UMLModel or KernelModel.
 */
export function generateOpenApiSpec(
  modelOrKernel: UMLModel | KernelModel,
  options: OpenApiGenerationOptions = {}
): OpenApiSpec {
  let kernel: KernelModel
  let modelTitle = "UmlStudio API"

  if ("entities" in modelOrKernel && "enums" in modelOrKernel) {
    kernel = modelOrKernel
  } else {
    modelTitle = modelOrKernel.title || modelTitle
    kernel = buildKernelModel(modelOrKernel, {
      packageName: options.packageName || "com.example.demo",
      selection: options.selection,
      inheritance: options.inheritance ?? "JOINED",
    })
  }

  const enumsMap = new Map<string, string[]>()
  for (const e of kernel.enums) {
    enumsMap.set(e.name, e.values)
  }

  const serverPort = options.serverPort ?? 9000
  const serverUrl = options.serverUrl || `http://localhost:${serverPort}`

  const servers: OpenApiServer[] = [
    {
      url: serverUrl,
      description: `Local Spring Boot 3.x server (port ${serverPort})`,
    },
  ]

  const tags: OpenApiTag[] = []
  const paths: Record<string, OpenApiPathItem> = {}
  const schemas: Record<string, OpenApiSchema> = {}

  // Register enums into schemas
  for (const e of kernel.enums) {
    schemas[e.name] = {
      type: "string",
      enum: e.values,
      description: `Enum ${e.name}`,
    }
  }

  // Register entity schemas and CRUD paths
  for (const entity of kernel.entities) {
    tags.push({
      name: entity.className,
      description: `REST endpoints for managing ${entity.className} entities`,
    })

    schemas[`${entity.className}Request`] = buildRequestSchema(entity, enumsMap)
    schemas[`${entity.className}Response`] = buildResponseSchema(entity, enumsMap)

    const { collectionPath, collectionItem, itemPath, itemItem } = buildEntityPaths(entity)
    paths[collectionPath] = collectionItem
    paths[itemPath] = itemItem
  }

  // Register standard ApiError schema
  schemas["ApiError"] = buildApiErrorSchema()

  const components: OpenApiComponents = {
    schemas,
  }

  return {
    openapi: "3.0.3",
    info: {
      title: options.title || modelTitle,
      version: options.version || "1.0.0",
      description:
        options.description ||
        `REST API specification generated automatically by UmlStudio from OMG UML 2.5 Class Diagram.`,
      contact: {
        name: "UmlStudio Codegen Engine",
        url: "https://umlstudio.com",
      },
    },
    servers,
    tags,
    paths,
    components,
  }
}
