import type {
  OpenApiSchema,
  OpenApiSpec,
  PostmanCollection,
  PostmanItem,
  PostmanRequest,
} from "./types.js"

/** Generates a sample JSON payload string from an OpenAPI schema. */
function generateSamplePayload(
  schema: OpenApiSchema | undefined,
  schemas: Record<string, OpenApiSchema> | undefined
): string {
  if (!schema) return "{}"

  if (schema.$ref && schemas) {
    const refKey = schema.$ref.replace("#/components/schemas/", "")
    const resolved = schemas[refKey]
    if (resolved) return generateSamplePayload(resolved, schemas)
  }

  if (schema.type === "object" && schema.properties) {
    const sampleObj: Record<string, unknown> = {}
    for (const [propKey, propSchema] of Object.entries(schema.properties)) {
      if (propSchema.example !== undefined) {
        sampleObj[propKey] = propSchema.example
      } else if (propSchema.type === "string") {
        sampleObj[propKey] = propSchema.enum ? propSchema.enum[0] : "sample_value"
      } else if (propSchema.type === "integer") {
        sampleObj[propKey] = 1
      } else if (propSchema.type === "number") {
        sampleObj[propKey] = 10.5
      } else if (propSchema.type === "boolean") {
        sampleObj[propKey] = true
      } else if (propSchema.type === "array") {
        sampleObj[propKey] = [1]
      } else {
        sampleObj[propKey] = "value"
      }
    }
    return JSON.stringify(sampleObj, null, 2)
  }

  return "{}"
}

/** Parses a URL path into host segments and path segments for Postman. */
function parsePostmanUrl(path: string): {
  raw: string
  host: string[]
  path: string[]
  variable?: { key: string; value: string; description?: string }[]
} {
  const normalized = path.replace(/\{([^}]+)\}/g, ":$1")
  const raw = `{{baseUrl}}${normalized}`
  const segments = normalized.split("/").filter(Boolean)
  const pathVariables: { key: string; value: string; description?: string }[] = []

  const matches = path.matchAll(/\{([^}]+)\}/g)
  for (const m of matches) {
    pathVariables.push({
      key: m[1],
      value: "1",
      description: `Path parameter ${m[1]}`,
    })
  }

  return {
    raw,
    host: ["{{baseUrl}}"],
    path: segments,
    ...(pathVariables.length > 0 ? { variable: pathVariables } : {}),
  }
}

/**
 * Transforms an OpenAPI 3.0.3 specification into a Postman Collection v2.1.0 document.
 */
export function generatePostmanCollection(
  spec: OpenApiSpec,
  collectionName?: string
): PostmanCollection {
  const name = collectionName || `${spec.info.title} - Postman Collection`
  const defaultBaseUrl = spec.servers[0]?.url || "http://localhost:9000"

  const entityFoldersMap = new Map<string, PostmanItem[]>()
  const generalItems: PostmanItem[] = []

  // Group operations by tag
  for (const [pathStr, pathItem] of Object.entries(spec.paths)) {
    const methods: ("get" | "post" | "put" | "delete")[] = ["get", "post", "put", "delete"]

    for (const method of methods) {
      const op = pathItem[method]
      if (!op) continue

      const tag = op.tags?.[0] || "General"
      const upperMethod = method.toUpperCase() as "GET" | "POST" | "PUT" | "DELETE"

      const headers = [
        {
          key: "Accept",
          value: "application/json",
          type: "text",
        },
      ]

      let body: PostmanRequest["body"] = undefined
      if (op.requestBody?.content?.["application/json"]) {
        headers.push({
          key: "Content-Type",
          value: "application/json",
          type: "text",
        })
        const reqSchema = op.requestBody.content["application/json"].schema
        body = {
          mode: "raw",
          raw: generateSamplePayload(reqSchema, spec.components.schemas),
          options: {
            raw: {
              language: "json",
            },
          },
        }
      }

      const postmanReq: PostmanRequest = {
        method: upperMethod,
        header: headers,
        url: parsePostmanUrl(pathStr),
        description: op.description || op.summary,
        ...(body ? { body } : {}),
      }

      const item: PostmanItem = {
        name: op.summary || `${upperMethod} ${pathStr}`,
        request: postmanReq,
        response: [],
      }

      if (!entityFoldersMap.has(tag)) {
        entityFoldersMap.set(tag, [])
      }
      entityFoldersMap.get(tag)!.push(item)
    }
  }

  const items: PostmanItem[] = []

  for (const [tag, folderItems] of entityFoldersMap.entries()) {
    items.push({
      name: tag,
      description: `CRUD operations for ${tag}`,
      item: folderItems,
    })
  }

  if (generalItems.length > 0) {
    items.push(...generalItems)
  }

  return {
    info: {
      _postman_id: "umlstudio-cu07-" + Math.random().toString(36).substring(2, 10),
      name,
      description: spec.info.description || "Generated by UmlStudio OpenAPI Exporter",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    item: items,
    variable: [
      {
        key: "baseUrl",
        value: defaultBaseUrl,
        type: "string",
      },
    ],
  }
}
