export const CANVAS = Object.freeze({
  MIN_SCALE_TO_ZOOM_OUT: 0.4,
  MAX_SCALE_TO_ZOOM_IN: 2.5,
  MOUSE_UP_OFFSET_PX: 5,
  SNAP_TO_GRID_PX: 5,
  EXTRA_SPACE_FOR_EXTENSION: 10,
  PASTE_OFFSET_PX: 20,
} as const)

const INTERFACE_SIZE = 30
const INTERFACE_RADIUS = INTERFACE_SIZE / 2
const INTERFACE_STROKE_WIDTH = 2
const INTERFACE_SOCKET_GAP = 4

export const INTERFACE = Object.freeze({
  SIZE: INTERFACE_SIZE,
  RADIUS: INTERFACE_RADIUS,
  STROKE_WIDTH: INTERFACE_STROKE_WIDTH,
  SOCKET_GAP: INTERFACE_SOCKET_GAP,
} as const)

export const EDGES = Object.freeze({
  MARKER_PADDING: -3,
  SOURCE_CONNECTION_POINT_PADDING: 3,
  STEP_BORDER_RADIUS: 0,
  EDGE_HIGHLIGHT_STROKE_WIDTH: 15,
  EDGE_LINE_JUMP_HEIGHT: 10,
  EDGE_LINE_JUMP_WIDTH: 16,
  STUB_LENGTH: 30,
  NODE_CLEARANCE_PX: 5 * CANVAS.SNAP_TO_GRID_PX,
  MIN_NODE_CLEARANCE_PX: 2 * CANVAS.SNAP_TO_GRID_PX,
  MIN_STUB_LENGTH: CANVAS.SNAP_TO_GRID_PX,
  BEND_HANDLE_SCREEN_LENGTH_PX: 34,
  BEND_HANDLE_MIN_SCREEN_LENGTH_PX: 18,
  MIN_ENDPOINT_HIT_TARGET_PX: 15,
  BEND_HANDLE_CORNER_CLEARANCE_PX: 10,
  BEND_HANDLE_SAFE_AREA_PX: 25,
  ENDPOINT_HIT_TARGET_SIZE: 24,
  ENDPOINT_HANDLE_CLEARANCE_PX: 4,
  BEND_SNAP_GRID_PX: CANVAS.SNAP_TO_GRID_PX,
  ORTHOGONAL_DOGLEG_TOLERANCE_PX: 2,
  ORTHOGONAL_ARM_OVERLAP_PX: 10,
  LABEL_GAP: 14,
  LABEL_LINE_HEIGHT: 14,
  LABEL_NOMINAL_HALF_EXTENT: 40,
  WAYPOINT_DRAG_THRESHOLD_PX: 6,
  WAYPOINT_COLLINEAR_TOLERANCE_PX: 4,
  WAYPOINT_COLLAPSE_SNAP_SCREEN_PX: 10,
  WAYPOINT_HANDLE_RADIUS_PX: 5,
  WAYPOINT_HIT_TARGET_PX: 24,
  WAYPOINT_GHOST_MIN_SEGMENT_PX: 64,
} as const)
