import { describe, it, expect } from "vitest"
import type { UMLModel } from "@umlstudio/core"
import {
  generateOpenApiSpec,
  generateOpenApiYaml,
  validateOpenApiSpec,
} from "../../src/openapi/index.js"

const SAMPLE_MODEL: UMLModel = {
  id: "model-unit-test",
  title: "InventoryApi",
  version: "4.0.0",
  type: "ClassDiagram" as UMLModel["type"],
  assessments: {},
  nodes: [
    {
      id: "node-product",
      type: "class",
      width: 200,
      height: 150,
      measured: { width: 200, height: 150 },
      data: {
        name: "Product",
        attributes: [
          { id: "a1", name: "+ id: Long" },
          { id: "a2", name: "+ name: String" },
          { id: "a3", name: "+ price: Double" },
          { id: "a4", name: "+ inStock: Boolean" },
          { id: "a5", name: "+ createdAt: LocalDateTime" },
        ],
        methods: [],
      },
      position: { x: 0, y: 0 },
    },
    {
      id: "node-category",
      type: "class",
      width: 200,
      height: 150,
      measured: { width: 200, height: 150 },
      data: {
        name: "Category",
        attributes: [
          { id: "c1", name: "+ id: Long" },
          { id: "c2", name: "+ code: String" },
        ],
        methods: [],
      },
      position: { x: 250, y: 0 },
    },
  ],
  edges: [
    {
      id: "edge-cat-prod",
      type: "ClassComposition",
      source: "node-category",
      target: "node-product",
      sourceHandle: "right",
      targetHandle: "left",
      data: {
        sourceMultiplicity: "1",
        targetMultiplicity: "0..*",
        label: "products",
        points: [],
      },
    },
  ],
}

describe("OpenAPI 3.0 Builder Unit Tests", () => {
  it("builds valid OpenAPI 3.0.3 specification object", () => {
    const spec = generateOpenApiSpec(SAMPLE_MODEL, {
      title: "InventoryApi",
      serverPort: 9000,
    })

    expect(spec.openapi).toBe("3.0.3")
    expect(spec.info.title).toBe("InventoryApi")
    expect(spec.servers).toHaveLength(1)
    expect(spec.servers[0]?.url).toBe("http://localhost:9000")

    // Check tags
    const tagNames = spec.tags.map((t) => t.name)
    expect(tagNames).toContain("Product")
    expect(tagNames).toContain("Category")

    // Check paths for Product
    expect(spec.paths["/api/products"]).toBeDefined()
    expect(spec.paths["/api/products"]?.get).toBeDefined()
    expect(spec.paths["/api/products"]?.post).toBeDefined()

    expect(spec.paths["/api/products/{id}"]).toBeDefined()
    expect(spec.paths["/api/products/{id}"]?.get).toBeDefined()
    expect(spec.paths["/api/products/{id}"]?.put).toBeDefined()
    expect(spec.paths["/api/products/{id}"]?.delete).toBeDefined()

    // Check path parameter id
    const getByIdParams = spec.paths["/api/products/{id}"]?.get?.parameters
    expect(getByIdParams).toBeDefined()
    expect(getByIdParams?.[0]?.name).toBe("id")
    expect(getByIdParams?.[0]?.in).toBe("path")
    expect(getByIdParams?.[0]?.required).toBe(true)
    expect(getByIdParams?.[0]?.schema.type).toBe("integer")

    // Check components schemas
    expect(spec.components.schemas).toBeDefined()
    const schemas = spec.components.schemas!
    expect(schemas["ProductRequest"]).toBeDefined()
    expect(schemas["ProductResponse"]).toBeDefined()
    expect(schemas["CategoryRequest"]).toBeDefined()
    expect(schemas["CategoryResponse"]).toBeDefined()
    expect(schemas["ApiError"]).toBeDefined()

    // Request schema should not include autogenerated id
    expect(schemas["ProductRequest"]?.properties?.["id"]).toBeUndefined()
    expect(schemas["ProductRequest"]?.properties?.["name"]?.type).toBe("string")
    expect(schemas["ProductRequest"]?.properties?.["price"]?.type).toBe("number")
    expect(schemas["ProductRequest"]?.properties?.["inStock"]?.type).toBe("boolean")

    // Response schema should include id
    expect(schemas["ProductResponse"]?.properties?.["id"]?.type).toBe("integer")
  })

  it("passes structural validation", () => {
    const spec = generateOpenApiSpec(SAMPLE_MODEL)
    const result = validateOpenApiSpec(spec)
    expect(result.valid).toBe(true)
    expect(result.errors).toHaveLength(0)
  })

  it("generates deterministic YAML string", () => {
    const spec = generateOpenApiSpec(SAMPLE_MODEL)
    const yaml = generateOpenApiYaml(spec)

    expect(yaml).toContain('openapi: "3.0.3"')
    expect(yaml).toContain("title: InventoryApi")
    expect(yaml).toContain('"/api/products":')
    expect(yaml).toContain("ProductRequest:")
  })
})
